image: Visual Studio 2017
platform: Any CPU
configuration: Release
before_build:
  - dotnet restore
build:
  project: Mandrill.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true

test_script:
  - dotnet test ./tests/Mandrill.Tests/Mandrill.Tests.csproj