image: Visual Studio 2017
platform: Any CPU
configuration: Release
before_build:
  - dotnet restore
build:
  project: Mandrill.sln
test_script:
  - dotnet test ./tests/Mandrill.Tests/Mandrill.Tests.csproj
artifacts:
  - path: ./src/Mandrill/bin/Release/**/*.*